import type { Metadata } from "next";
import { ReactNode } from 'react';
import { Inter, Roboto_Mono } from 'next/font/google';
import '@/styles/globals.css';

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});

const mono = Roboto_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "KukuIT Flatform",
  description: "Generated by KukuIT",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: string };
}) {

  return (
    <html lang={params.locale}>
      <body className={`${inter.variable} ${mono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
