import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Inter, Roboto_Mono } from 'next/font/google';
import { NextIntlClientProvider, useMessages } from "next-intl";
import { headers } from "next/headers";
import { notFound } from 'next/navigation';
import '@/styles/globals.css';

// Font cấu hình
const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});
const mono = Roboto_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
});
// Metadata cho trang
export const metadata: Metadata = {
  title: 'KukuIT Flatform',
  description: 'Generated by KukuIT',
};

// Layout đa ngôn ngữ
export default function LocaleLayout({ children }: { children: React.ReactNode }) {
  const messages = useMessages();
  const headersList = headers();
  const locale = headersList.get("x-locale") || "vi";

  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${mono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
