// src/app/[locale]/layout.tsx
import type { Metadata } from "next";
import { ReactNode } from 'react';
import { Inter, Roboto_Mono } from 'next/font/google';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { notFound } from 'next/navigation';
import '@/styles/globals.css';

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});

const mono = Roboto_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "KukuIT Flatform",
  description: "Generated by KukuIT",
};

export default async  function LocaleLayout({
  children,
  params: {locale}
}: {
  children: ReactNode;
  params: {locale: string};
}) {
  let messages;
  try {
    messages = (await import(`../../locales/${locale}.json`)).default;
  } catch (error) {
    // fallback: nếu không có locale này thì load mặc định
    messages = (await import('../../locales/vi.json')).default;
  }

  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${mono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
